import { SongData } from '../model/SongData';

export class DataModel {
  public static readonly LOFI: SongData[] = [
    {
      id: 1,
      title: 'Dream It Possible',
      artist: 'Delacey',
      artwork: $r('app.media.ic_dream_it'),
      src: 'lofi1.mp3'
    },
    {
      id: 2,
      title: 'Dream It Possible',
      artist: 'Delacey',
      artwork: $r('app.media.ic_dream_it'),
      src: 'lofi2.mp3'
    },
  ]

  public static readonly RAIN: SongData[] = [
    {
      id: 1,
      title: 'Dream It Possible',
      artist: 'Delacey',
      artwork: $r('app.media.ic_dream_it'),
      src: 'rain1.mp3'
    },
    {
      id: 2,
      title: 'Dream It Possible',
      artist: 'Delacey',
      artwork: $r('app.media.ic_dream_it'),
      src: 'rain2.mp3'
    },
  ]

  public static readonly COFFEE_SHOP: SongData[] = [
    {
      id: 1,
      title: 'Dream It Possible',
      artist: 'Delacey',
      artwork: $r('app.media.ic_dream_it'),
      src: 'coffee_shop1.mp3'
    },
    {
      id: 2,
      title: 'Dream It Possible',
      artist: 'Delacey',
      artwork: $r('app.media.ic_dream_it'),
      src: 'coffee_shop2.mp3'
    },
  ]

  public static readonly FIREPLACE: SongData[] = [
    {
      id: 1,
      title: 'Dream It Possible',
      artist: 'Delacey',
      artwork: $r('app.media.ic_dream_it'),
      src: 'fireplace1.mp3'
    },
    {
      id: 2,
      title: 'Dream It Possible',
      artist: 'Delacey',
      artwork: $r('app.media.ic_dream_it'),
      src: 'fireplace2.mp3'
    },
  ]

  public static readonly WAVES_OCEAN: SongData[] = [
    {
      id: 1,
      title: 'Dream It Possible',
      artist: 'Delacey',
      artwork: $r('app.media.ic_dream_it'),
      src: 'waves_ocean1.mp3'
    },
    {
      id: 2,
      title: 'Dream It Possible',
      artist: 'Delacey',
      artwork: $r('app.media.ic_dream_it'),
      src: 'waves_ocean2.mp3'
    },
  ]
  public static readonly FOREST_BIRDS: SongData[] = [
    {
      id: 1,
      title: 'Dream It Possible',
      artist: 'Delacey',
      artwork: $r('app.media.ic_dream_it'),
      src: 'birds1.mp3'
    },
    {
      id: 2,
      title: 'Dream It Possible',
      artist: 'Delacey',
      artwork: $r('app.media.ic_dream_it'),
      src: 'birds2.mp3'
    },
  ]

  public static readonly WHITE_NOISE: SongData[] = [
    {
      id: 1,
      title: 'Dream It Possible',
      artist: 'Delacey',
      artwork: $r('app.media.ic_dream_it'),
      src: 'white_noise1.mp3'
    },
    {
      id: 2,
      title: 'Dream It Possible',
      artist: 'Delacey',
      artwork: $r('app.media.ic_dream_it'),
      src: 'white_noise2.mp3'
    },
  ]
}